name: d9_dream_app
publish_to: 'none'
description: Dream analysis Flutter app (BLoC + Firebase Auth + speech-to-text)
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  dio: ^5.4.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  speech_to_text: ^6.6.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
