name: d9_dream_app
publish_to: 'none'
description: Dream analysis app using Flutter + BLoC + Firebase auth and STT/TTS.
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  http: ^1.2.1
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.3
  intl: ^0.19.0
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
